- name: Demo-Variable declared inside a Play
  hosts: jumpbox
  tasks: 
  - name: print Message
    vars:
     Variable: User variable
    ansible.builtin.debug:
      msg: This is a {{Variable}}

- name: Demo-Variable declared in a file
  hosts: webserver
  vars_files:
    - password.yml
  tasks: 
  - name: print Message
    ansible.builtin.debug:
      msg: This is a {{Variable}}


- name: Demo-Variable declared in Inventory_hostFile
  hosts: webserver
  tasks: 
  - name: print Message
    ansible.builtin.debug:
      msg: This is a not declared in play or file {{Variable}}

- name: Demo-Variable declared at the end
  hosts: webserver
  tasks: 
  - name: print Message
    ansible.builtin.debug:
      msg: This is a {{Variable}}
    vars:
      Variable: User variable

- name: Learn System Variable Facts/prdefined variables
  hosts: jumpbox
  tasks: 
    - name: Use of System variables
      ansible.builtin.debug:
        msg: This is you User name {{ansible_hostname}}


# - name: Register a variable
#   hosts: jumpbox
#   tasks:
#   - name: Get UpTime
#     ansible.inbuilt.shell: uptime
#     register: out
#   - name: Get the up time from the defined variable
#     ansible.inbuilt.debug:
#      msg: "{{out.stdout}}"
      

- name: Register a variable
  hosts: jumpbox
  tasks:
    - name: Get UpTime
      shell: uptime   # 'ansible.inbuilt' is not required, use just 'shell'
      register: out
    - name: Get the up time from the defined variable
      debug:
        msg: "{{ out.stdout }}\"   # Extra indentation was removed, and there must be a space after ':' in \"{{ out.stdout }}"

- name: Register a variable-Test Demo
  hosts: jumpbox
  tasks:
    - name: Get UpTime Test demo only out which is register
      shell: uptime   # 'ansible.inbuilt' is not required, use just 'shell'
      register: out
    - name: Get the up time from the defined variable
      debug:
        msg: "{{ out.stdout }}\"   # Extra indentation was removed, and there must be a space after ':' in \"{{ out.stdout }}"


- name: Demo of Facts-Setting up variables
  hosts: jumpbox
  tasks:
    - name: Get UpTime Test demo only out which is register
      shell: uptime   # 'ansible.inbuilt' is not required, use just 'shell'
      register: out
    - name: Setting up Variable/Fact
      ansible.builtin.set_fact:
        fact1: "{{outstdout}}"
    - name: Print the fact
      ansible.builtin.debug:
        msg: "{{fact1}}"


