- name: Learn Loops Ex1
  hosts: jumpbox
  tasks:
    - name: Simple Loops
      ansible.builtin.debug:
        msg: The fruit is {{item}}
      loop:
       - Apple
       - Beetroot
       - Carrot
  tasks:
    - name: Dictionary loop
      ansible.builtin.debug:
        msg: I have {{ item.quantity }} {{item.fruit}}
      loop:
        - {fruit: apple , quantity: 10}
        - {fruit: PineApple,quantity: 20}
       