- name: Demo of Conditions
  hosts: jumpbox
  tasks:
    - name: Simple conditions in Ansible
      ansible.builtin.debug:
       msg: "The Selinux is disabled"
      when: ansible_selinux.status == "disabled"